CREATE DEFINER=`root`@`localhost` PROCEDURE `CREATE_ACCESSLOG`(
	IN `_IPADDR` VARCHAR(20),
	IN `_USERID` VARCHAR(60),
	OUT `_RESMSG` VARCHAR(50)
)
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT ''
BEGIN
	DECLARE TIMEVALUE VARCHAR(50);
	DECLARE DATEVALUE VARCHAR(50);
	DECLARE HITCOUNT INT(11);
	
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	 GET DIAGNOSTICS CONDITION 1 
    @sql_state = RETURNED_SQLSTATE, 
    @sql_errno = MYSQL_ERRNO, 
    @sql_msg   = MESSAGE_TEXT;
   SELECT  @sql_state,  @sql_errno, @sql_msg;
		SET _RESMSG = 'SQLEXCEPTION';
		ROLLBACK;
	END;
	
	 SELECT @HITCOUNT := HIT 
	 FROM ACCESSLOG 
	 WHERE USERID = _USERID OR IPADDR = _IPADDR 
	 ORDER BY HIT DESC 
	 LIMIT 1;
	 
	 SET @DATEVALUE := CURDATE();
	 SET @TIMEVALUE := CURTIME();
	
	SELECT @HITCOUNT;
	
	START TRANSACTION;
		IF @HITCOUNT IS NULL THEN
			INSERT INTO accesslog(IPADDR,ACCESSDATE,ACCESSTIME,USERID,HIT) VALUES(_IPADDR,@DATEVALUE,@TIMEVALUE,_USERID,1);
		ELSE
			INSERT INTO ACCESSLOG(IPADDR,ACCESSDATE,ACCESSTIME,USERID,HIT) VALUES(_IPADDR,@DATEVALUE,@TIMEVALUE,_USERID,@HITCOUNT+1);
		END IF;
		
		SET @HITCOUNT = 0;
		SET _RESMSG = 'SUCCESS';
		
	COMMIT;
	
END